.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "ROFI\-FILE\-BROWSER\-EXTENDED" "1" "January 2022" ""
.SH "NAME"
\fBrofi\-file\-browser\-extended\fR \- use rofi to quickly open files
.SH "SYNOPSIS"
\fBrofi \-show file\-browser\-extended [ \-file\-browser\-dir <dir> ] [ \-file\-browser\-cmd <cmd> ]\fR
.br
\fBrofi \-show file\-browser\-extended [ \-file\-browser\-depth <depth> ] [ \-file\-browser\-follow\-symlinks ]\fR
.br
\fBrofi \-show file\-browser\-extended [ \-file\-browser\-oc\-cmd <cmd> ] [ \-file\-browser\-oc\-search\-path ]\fR
.br
\fBfd | rofi \-show file\-browser\-extended \-file\-browser\-stdin\fR
.SH "DESCRIPTION"
\fBrofi\-file\-browser\-extended\fR is a configurable file browser plugin for rofi\. It\'s main use case is to quickly open files without having to open a window to navigate to the file\.
.SH "USAGE"
.SS "Resuming from the last opened directory"
Use \fB\-file\-browser\-resume\fR to enable this behaviour\. The plugin will write the current directory to the "resume file" before exiting, and read it on startup\. The default resume file location is \fB$XDG_USER_CONFIG_DIR/rofi/file\-browser\-resume\fR (usually \fB$HOME/config/rofi/file\-browser\-resume\fR)\. A different resume file can be chosen via \fB\-file\-browser\-resume\-file\fR\.
.SS "Listing files recursively"
\fB\-file\-browser\-depth\fR can be used to list files recursively up to a certain depth\. A depth of 0 means files are listed without a depth limit\.
.P
Symlinks are not followed by default\. \fB\-file\-browser\-follow\-symlinks\fR can be used to follow symlinks\. When symlinks are followed, every file is still only reported once\.
.SS "Opening files with custom commands"
Press the \fBopen custom\fR key (see \fIKey bindings\fR) to enter \fBopen custom\fR mode on the selected file\. The plugin will then display a list of commands to open the selected file with\.
.IP "\[ci]" 4
All executables in \fB$PATH\fR can be added to this list with \fB\-file\-browser\-oc\-search\-path\fR\.
.IP "\[ci]" 4
User\-defined commands can be added with \fB\-file\-browser\-oc\-cmd\fR (multiple by passing the option multiple times)\.
.IP "\[ci]" 4
If no commands are specified, the file to be opened will be shown instead of a list of commands\.
.IP "" 0
.P
User\-defined commands can optionally specify an icon and a display name (with pango markup)\.
.P
Format:
.IP "" 4
.nf
<command>;icon:<icon\-name>;name:<name\-to\-displayed>
.fi
.IP "" 0
.P
\fBicon\fR and \fBname\fR are optional\. The order of \fBicon\fR and \fBname\fR does not matter as long as the command comes first\.
.P
Example:
.IP "" 4
.nf
\-file\-browser\-oc\-cmd "gimp"
\-file\-browser\-oc\-cmd "pcmanfm\-qt;name:pcmanfm;icon:system\-file\-manager"
\-file\-browser\-oc\-cmd "deadbeef \-\-queue;icon:deadbeef;name:deadbeef <i>(queue)</i>"
.fi
.IP "" 0
.SS "Reading paths from stdin"
\fB\-file\-browser\-stdin\fR can be used to read displayed paths from stdin\. Paths must either be relative to the starting directory (\fB\-file\-browser\-dir\fR) or absolute\. It is not checked if the paths actually exist\. The paths are not sorted or matched to any exclude patters\.
.P
After reading the paths, the plugin behaves no different than usual\. You may want to use this option with \fB\-file\-browser\-no\-descend\fR and / or \fB\-file\-browser\-stdout\fR to make it more dmenu\-like\.
.P
Example:
.IP "" 4
.nf
fd | rofi \-show file\-browser\-extended \-file\-browser\-stdin
fd \-a | rofi \-show file\-browser\-extended \-file\-browser\-stdin
ls somedir | rofi \-show file\-browser\-extended \-file\-browser\-stdin \-file\-browser\-dir somedir
.fi
.IP "" 0
.SH "CONFIGURATION"
The default config file location is \fB$XDG_USER_CONFIG_DIR/rofi/file\-browser\fR (usually to \fB$HOME/config/rofi/file\-browser\fR)\. The config file consists of newline\-separated command line options \fBwithout\fR the \fB"\-file\-browser\-"\fR prefix\.
.P
Example:
.IP "" 4
.nf
cmd        "exo\-open"
oc\-cmd     "evince;icon:evince"
oc\-cmd     "gimp;icon:gimp"
depth      2

open\-parent\-as\-self
.fi
.IP "" 0
.P
Comments start with \fB#\fR\. Quotes inside string arguments must not be escaped\. Escape sequences are currently not supported\.
.P
Command line options will override the config file (or add to the config file arguments if the option can be specified multiple times)\. A different config file can be specified with \fB\-file\-browser\-config\fR (multiple by passing the option multiple times)\. All command line options but \fB\-file\-browser\-config\fR itself can be used in the config file\.
.SH "KEY BINDINGS"
.IP "\[ci]" 4
\fBkb\-accept\-alt\fR, \fI(default: Shift+Return)\fR
.IP
\fBopen custom\fR: Open the selected file with a custom command\.
.IP "\[ci]" 4
\fBkb\-custom\-1\fR, \fI(default: Alt+1)\fR
.IP
\fBopen multi\fR: Open the selected file without closing rofi\. Can be used in the prompt of \fBopen custom\fR\.
.IP "\[ci]" 4
\fBkb\-custom\-2\fR, \fI(default: Alt+2)\fR
.IP
Toggle hidden files\.
.IP "" 0
.P
Key bindings can be changed via command line options (see \fICommand line options/Key bindings\fR)\.
.SH "OPTIONS"
.SS "Behaviour"
.TP
\fB\-file\-browser\-cmd\fR \fI\fIcmd\fR\fR
Set the command to open selected files with\. \fB(default: \fBxdg\-open\fR)\fR
.TP
\fB\-file\-browser\-dir\fR \fI\fIpath\fR\fR
Set the starting directory\. \fB(default: current working directory)\fR
.TP
\fB\-file\-browser\-resume\fR
Resume from the last opened directory\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-resume\-file\fR \fI\fIpath\fR\fR
Set the resume file\. When resuming is enabled, the path of the last opened directory is saved to this file\. \fB(default: \fB$XDG_USER_CONFIG_DIR/rofi/file\-browser\-resume\fR)\fR
.TP
\fB\-file\-browser\-depth\fR \fI\fIdepth\fR\fR
List files recursively until a depth is reached\. A value of 0 means no depth limit\. \fB(default: 1)\fR
.TP
\fB\-file\-browser\-follow\-symlinks\fR
Follow symlinks when listing files recursively\. \fB(default: don\'t follow symlinks)\fR
.IP
When symlinks are followed, every file is still only reported once\.
.TP
\fB\-file\-browser\-show\-hidden\fR
Show hidden files\. \fB(default: hidden)\fR
.TP
\fB\-file\-browser\-only\-dirs\fR
Only show directories\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-only\-files\fR
Only show files\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-no\-descend\fR
Open directories instead of descending into them\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-open\-parent\-as\-self\fR
Treat the parent directory (\fB\.\.\fR) as the current directory when opened\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-exclude\fR
Exclude paths by matching the basename to glob patterns\. \fB(default: none)\fR
.IP
Supports \fB*\fR and \fB?\fR\.
.TP
\fB\-file\-browser\-stdin\fR
Read paths from stdin\. \fB(default: disabled)\fR
.IP
Paths must either be relative to the starting directory (\fB\-file\-browser\-dir\fR) or absolute\. It is not checked if the files actually exist\. The paths are not sorted or matched to any exclude patters\.
.TP
\fB\-file\-browser\-stdout\fR
Instead of opening files, print absolute paths of selected files to stdout\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-oc\-search\-path\fR
Search \fB$PATH\fR for executables and display them in \fBopen custom\fR mode (after user\-defined commands)\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-oc\-cmd\fR \fI\fIcmd\fR\fR
Specify user\-defined commands to be displayed in \fBopen custom\fR mode\. \fB(default: none)\fR
.IP
Format: \fB<command>;icon:<icon\-name>;name:<name\-to\-displayed>\fR
.IP
\fBicon\fR and \fBname\fR are optional\. The order of \fBicon\fR and \fBname\fR does not matter as long as the command comes first\. \fBname\fR may use pango markup\.
.TP
\fB\-file\-browser\-sort\-by\-type\fR, \fB\-file\-browser\-no\-sort\-by\-type\fR
Enable / disable sort\-by\-type (directories first, files second, inaccessible directories last)\. \fB(default: enabled)\fR
.TP
\fB\-file\-browser\-sort\-by\-depth\fR, \fB\-file\-browser\-no\-sort\-by\-depth\fR
Enable / disable sort\-by\-depth when listing files recursively\. Sort\-by\-type is secondary to sort\-by\-depth if both are enabled\. \fB(default: disabled)\fR
.TP
\fB\-file\-browser\-hide\-parent\fR
Hide the parent directory (\fB\.\.\fR)\. \fB(default: shown)\fR
.TP
\fB\-file\-browser\-config\fR \fI\fIpath\fR\fR
Load options from the specified config file\. \fB(default: \fB$XDG_USER_CONFIG_DIR/rofi/file\-browser\fR)\fR
.IP
Can be used multiple times to load options from multiple config files\. When this option is specified, the default config file will not be loaded\.
.SS "Key bindings"
Supported key bindings are \fBkb\-accept\-alt\fR, \fBkb\-custom\-[0\-19]\fR and \fBnone\fR (disables the key binding)\. You can change the actual key bindings that correspond to \fBkb\-accept\-alt\fR and \fBkb\-custom\-*\fR in rofi\'s options\. Run \fBrofi \-show keys\fR to display rofi\'s key bindings and what they are bound to\. Run \fBrofi \-dump\-config\fR or \fBrofi \-dump\-xresources\fR to get a list of available options\.
.TP
\fB\-file\-browser\-open\-custom\-key\fR \fI\fIrofi\-key\fR\fR
Set the key binding for \fBopen custom\fR\. \fB(default: \fBkb\-accept\-alt\fR)\fR
.TP
\fB\-file\-browser\-open\-multi\-key\fR \fI\fIrofi\-key\fR\fR
Set the key binding for \fBopen multi\fR\. \fB(default: \fBkb\-custom\-1\fR)\fR
.TP
\fB\-file\-browser\-open\-toggle\-hidden\fR \fI\fIrofi\-key\fR\fR
Set the key binding for toggling hidden files\. \fB(default: \fBkb\-custom\-2\fR)\fR
.SS "Appearance"
.TP
\fB\-file\-browser\-disable\-icons\fR
Disable icons\. \fB(default: enabled)\fR
.TP
\fB\-file\-browser\-disable\-thumbnails\fR
Disable thumbnails for image files\. \fB(default: enabled)\fR
.TP
\fB\-file\-browser\-disable\-status\fR
Disable the status line that shows the current path\. \fB(default: enabled)\fR
.TP
\fB\-file\-browser\-path\-sep\fR \fI\fIstring\fR\fR
Set the path separator for the status line\. \fB(default: \fB" / "\fR)\fR
.TP
\fB\-file\-browser\-hide\-hidden\-symbol\fR \fI\fIstring\fR\fR
Set the indicator that hidden files are hidden\. \fB(default: \fB"[\-]"\fR)\fR
.TP
\fB\-file\-browser\-show\-hidden\-symbol\fR \fI\fIstring\fR\fR
Set the indicator that hidden files are shown\. \fB(default: \fB"[+]"\fR)\fR
.TP
\fB\-file\-browser\-up\-text\fR \fI\fIstring\fR\fR
Set the text for the parent directory\. \fB(default: \fB"\.\."\fR)\fR\.
.TP
\fB\-file\-browser\-up\-icon\fR \fI\fIicon\-name\fR\fR
Set the icon for the parent directory\. \fB(default: \fB"go\-up"\fR)\fR
.TP
\fB\-file\-browser\-fallback\-icon\fR \fI\fIicon\-name\fR\fR
Set the fallback icon used for files without icons (e\.g\. block devices)\. \fB(default: \fB"text\-x\-generic"\fR)\fR
.TP
\fB\-file\-browser\-inaccessible\-icon\fR \fI\fIicon\-name\fR\fR
Set the icon for inaccessible directories\. \fB(default: \fB"error"\fR)\fR
.SH "TROUBLESHOOTING"
If you encounter a problem, try running rofi from the command line\. The plugin prints error messages if things go wrong\. If that doesn\'t help, feel free to create a new issue on GitHub\.
.SH "SEE ALSO"
rofi(1), nftw(3)
